export const WORLD_SCALE = 60;
export const PLAYER_SPEED = 2.6; // units per second
export const PLAYER_ANGULAR_SPEED = Math.PI; // radians per second
export const FIXED_DT = 1 / 120;
export const FOV = (110 * Math.PI) / 180;
export const STRIP_HEIGHT = 14;
export const FOG_DISTANCE = 24;
export const FOG_GAMMA = 1.8;
export const MAX_RAY_COUNT = 800;
export const MIN_RAY_COUNT = 320;
export const LINE_AGENT_WIDTH = 0.2;
export const WORLD_FOG_COLOR = "#1b1b1f";
export const HUD_WIDTH = 320;
export const DIALOGUE_WIDTH = 360;
export const EXPERT_KEY = "x";
export const TALK_KEY = "t";
export const ENTER_ROOM_KEY = "f";
export const LOSE_SIDES_THRESHOLD = 3;
